.TH "libjpconj Directory Reference" 3 "Tue Aug 29 2017" "Version 1.0" "JapKatsuyou.libJpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libjpconj Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinflection\&.cpp\fP"
.br
.ti -1c
.RI "file \fBinflection\&.h\fP"
.br
.ti -1c
.RI "file \fBjpconj\&.cpp\fP"
.br
.ti -1c
.RI "file \fBjpconj\&.h\fP"
.br
.ti -1c
.RI "file \fBjpconj_global\&.h\fP"
.br
.ti -1c
.RI "file \fBlemmatization\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlemmatization\&.h\fP"
.br
.ti -1c
.RI "file \fBtypeDefs\&.h\fP"
.br
.ti -1c
.RI "file \fBverbstem\&.cpp\fP"
.br
.ti -1c
.RI "file \fBverbstem\&.h\fP"
.br
.in -1c
