.TH "libjpconj/inflection.cpp" 3 "Tue Aug 29 2017" "Version 1.0" "JapKatsuyou.libJpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libjpconj/inflection.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inflection\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.libJpConj from the source code\&.
