.TH "libjpconj/jpconj.h" 3 "Tue Aug 29 2017" "Version 1.0" "JapKatsuyou.libJpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libjpconj/jpconj.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'jpconj_global\&.h'\fP
.br
\fC#include 'typeDefs\&.h'\fP
.br
\fC#include 'inflection\&.h'\fP
.br
\fC#include 'lemmatization\&.h'\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QList>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJpConj\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.libJpConj from the source code\&.
