.TH "libjpconj/jpconj.cpp" 3 "Tue Aug 29 2017" "Version 1.0" "JapKatsuyou.libJpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libjpconj/jpconj.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'jpconj\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QList< \fBVerbInfo\fP > \fBdeConjugate\fP (QString conjVerb)"
.br
.RI "\fIdeConjugate \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "QList<\fBVerbInfo\fP> deConjugate (QString conjVerb)"

.PP
deConjugate 
.PP
\fBParameters:\fP
.RS 4
\fIconjVerb\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.libJpConj from the source code\&.
