.TH "VerbInfo" 3 "Tue Aug 29 2017" "Version 1.0" "JapKatsuyou.libJpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VerbInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <typeDefs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBverb\fP"
.br
.ti -1c
.RI "\fBCForm\fP \fBform\fP"
.br
.ti -1c
.RI "\fBPolarity\fP \fBpolarity\fP"
.br
.ti -1c
.RI "\fBPoliteness\fP \fBpoliteness\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBCForm\fP VerbInfo::form"

.SS "\fBPolarity\fP VerbInfo::polarity"

.SS "\fBPoliteness\fP VerbInfo::politeness"

.SS "QString VerbInfo::verb"


.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.libJpConj from the source code\&.
