.TH "jpconj/Func Directory Reference" 3 "Tue Aug 29 2017" "Version 2.0.0" "JapKatsuyou.JpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpconj/Func Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBedict2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBedict2\&.h\fP"
.br
.ti -1c
.RI "file \fBjtrans\&.cpp\fP"
.br
.ti -1c
.RI "file \fBjtrans\&.h\fP"
.br
.ti -1c
.RI "file \fBtatoeba\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtatoeba\&.h\fP"
.br
.in -1c
