.TH "About" 3 "Tue Aug 29 2017" "Version 2.0.0" "JapKatsuyou.JpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
About \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <about\&.h>\fP
.PP
Inherits \fBQDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbout\fP (QWidget *parent=0)"
.br
.RI "\fI\fBAbout::About\fP The constructor of the Dialog box 'About'\&. \fP"
.ti -1c
.RI "\fB~About\fP ()"
.br
.RI "\fI\fBAbout::~About\fP The destructor of the Dialog box 'About'\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class is used to manage 'About' dialog box\&. It initialize the dialog components, and charge information in the current language 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "About::About (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBAbout::About\fP The constructor of the Dialog box 'About'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.SS "About::~About ()"

.PP
\fBAbout::~About\fP The destructor of the Dialog box 'About'\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.JpConj from the source code\&.
