.TH "jpconj/Ui/about.cpp" 3 "Tue Aug 29 2017" "Version 2.0.0" "JapKatsuyou.JpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpconj/Ui/about.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'about\&.h'\fP
.br
\fC#include 'ui_about\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.JpConj from the source code\&.
