.TH "jpconj/Ui/about.h" 3 "Tue Aug 29 2017" "Version 2.0.0" "JapKatsuyou.JpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpconj/Ui/about.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'UiHelper/language\&.h'\fP
.br
\fC#include <QDesktopServices>\fP
.br
\fC#include <QDialog>\fP
.br
\fC#include <QResource>\fP
.br
\fC#include <QUrl>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbout\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.JpConj from the source code\&.
