.TH "HelpNetworkReply" 3 "Tue Aug 29 2017" "Version 2.0.0" "JapKatsuyou.JpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelpNetworkReply \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQNetworkReply\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHelpNetworkReply\fP (const QNetworkRequest &request, const QByteArray &fileData, const QString &mimeType)"
.br
.ti -1c
.RI "virtual void \fBabort\fP ()"
.br
.ti -1c
.RI "virtual qint64 \fBbytesAvailable\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual qint64 \fBreadData\fP (char *data, qint64 maxlen)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HelpNetworkReply::HelpNetworkReply (const QNetworkRequest & request, const QByteArray & fileData, const QString & mimeType)"

.SH "Member Function Documentation"
.PP 
.SS "void HelpNetworkReply::abort ()\fC [virtual]\fP"

.SS "virtual qint64 HelpNetworkReply::bytesAvailable () const\fC [inline]\fP, \fC [virtual]\fP"

.SS "qint64 HelpNetworkReply::readData (char * data, qint64 maxlen)\fC [protected]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.JpConj from the source code\&.
