.TH "HelpPage" 3 "Tue Aug 29 2017" "Version 2.0.0" "JapKatsuyou.JpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelpPage \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQWebPage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHelpPage\fP (QWidget *central, QHelpEngine *engine, \fBQObject\fP *parent)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBQWebPage\fP * \fBcreateWindow\fP (QWebPage::WebWindowType)"
.br
.ti -1c
.RI "virtual bool \fBacceptNavigationRequest\fP (QWebFrame *frame, const QNetworkRequest &request, NavigationType type)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HelpPage::HelpPage (QWidget * central, QHelpEngine * engine, \fBQObject\fP * parent)"

.SH "Member Function Documentation"
.PP 
.SS "bool HelpPage::acceptNavigationRequest (QWebFrame * frame, const QNetworkRequest & request, NavigationType type)\fC [protected]\fP, \fC [virtual]\fP"

.SS "\fBQWebPage\fP * HelpPage::createWindow (QWebPage::WebWindowType)\fC [protected]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.JpConj from the source code\&.
