.TH "jpconj/Ui/helpviewer.h" 3 "Tue Aug 29 2017" "Version 2.0.0" "JapKatsuyou.JpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpconj/Ui/helpviewer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QAction>\fP
.br
\fC#include <QByteArray>\fP
.br
\fC#include <QDesktopServices>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QEvent>\fP
.br
\fC#include <QHelpEngine>\fP
.br
\fC#include <QKeyEvent>\fP
.br
\fC#include <QNetworkAccessManager>\fP
.br
\fC#include <QNetworkReply>\fP
.br
\fC#include <QNetworkRequest>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include <QVariant>\fP
.br
\fC#include <QWebView>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHelpViewer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.JpConj from the source code\&.
