.TH "jpconjmain" 3 "Tue Aug 29 2017" "Version 2.0.0" "JapKatsuyou.JpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpconjmain \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpconjmain\&.h>\fP
.PP
Inherits \fBQMainWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBjpconjmain\fP (QWidget *parent=0)"
.br
.RI "\fI\fBjpconjmain::jpconjmain\fP The constructor of the main window \fP"
.ti -1c
.RI "\fB~jpconjmain\fP ()"
.br
.RI "\fI\fBjpconjmain::~jpconjmain\fP The destructor of the main window \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBchangeEvent\fP (QEvent *event)"
.br
.RI "\fI\fBjpconjmain::changeEvent\fP The event treated here is the change of language\&. \fP"
.ti -1c
.RI "void \fBcloseEvent\fP (QCloseEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is used to manage the main window of the application\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "jpconjmain::jpconjmain (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBjpconjmain::jpconjmain\fP The constructor of the main window 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.SS "jpconjmain::~jpconjmain ()"

.PP
\fBjpconjmain::~jpconjmain\fP The destructor of the main window 
.SH "Member Function Documentation"
.PP 
.SS "void jpconjmain::changeEvent (QEvent * event)\fC [protected]\fP"

.PP
\fBjpconjmain::changeEvent\fP The event treated here is the change of language\&. 
.PP
\fBParameters:\fP
.RS 4
\fIevent\fP 
.RE
.PP

.SS "void jpconjmain::closeEvent (QCloseEvent * event)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.JpConj from the source code\&.
