.TH "jpconj/Ui/jpconjhelp.h" 3 "Tue Aug 29 2017" "Version 2.0.0" "JapKatsuyou.JpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpconj/Ui/jpconjhelp.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'helpviewer\&.h'\fP
.br
\fC#include 'UiHelper/language\&.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QEventLoop>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QHelpEngine>\fP
.br
\fC#include <QHelpContentWidget>\fP
.br
\fC#include <QHelpIndexWidget>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <QWebFrame>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjpconjhelp\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.JpConj from the source code\&.
