.TH "jpconj/UiHelper/jpconjtray.h" 3 "Tue Aug 29 2017" "Version 2.0.0" "JapKatsuyou.JpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpconj/UiHelper/jpconjtray.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include <QIcon>\fP
.br
\fC#include <QInputContext>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QPoint>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QSystemTrayIcon>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJpconjTray\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.JpConj from the source code\&.
