.TH "jpconjhelp" 3 "Tue Aug 29 2017" "Version 2.0.0" "JapKatsuyou.JpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpconjhelp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpconjhelp\&.h>\fP
.PP
Inherits \fBQMainWindow\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBindexInputChanged\fP (const QString &filter, const QString &wildcard=QString())"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBjpconjhelp\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~jpconjhelp\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBexists\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcloseEvent\fP (QCloseEvent *event)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "jpconjhelp::jpconjhelp (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "jpconjhelp::~jpconjhelp ()"

.SH "Member Function Documentation"
.PP 
.SS "void jpconjhelp::closeEvent (QCloseEvent * event)\fC [protected]\fP"

.SS "bool jpconjhelp::exists ()\fC [static]\fP"

.SS "void jpconjhelp::indexInputChanged (const QString & filter, const QString & wildcard = \fCQString()\fP)\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.JpConj from the source code\&.
