.TH "jpconj/Func/jtrans.h" 3 "Tue Aug 29 2017" "Version 2.0.0" "JapKatsuyou.JpConj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpconj/Func/jtrans.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br
\fC#include <QHash>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QRegExp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJTrans\fP"
.br
.RI "\fIThe \fBJTrans\fP class is used to romanize hiragana and katakana\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JapKatsuyou\&.JpConj from the source code\&.
